capp/carbon_app/forms.py
from flask_wtf import FlaskForm
from wtforms import  SubmitField,  SelectField,  FloatField
from wtforms.validators import InputRequired

class BusForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Petrol', 'Petrol'), ('No Fossil Fuel', 'No Fossil Fuel')])
  submit = SubmitField('Submit')

class CarForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('No Fossil Fuel', 'No Fossil Fuel')])
  submit = SubmitField('Submit')  

class PlaneForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Petrol', 'Petrol')])
  submit = SubmitField('Submit')
  
class FerryForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Diesel', 'Diesel'), ('CNG', 'CNG'), ('No Fossil Fuel', 'No Fossil Fuel')])
  submit = SubmitField('Submit')  

class MotorbikeForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Petrol', 'Petrol'), ('No Fossil Fuel', 'No Fossil Fuel')])
  submit = SubmitField('Submit')

class BicycleForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('No Fossil Fuel', 'No Fossil Fuel')])
  submit = SubmitField('Submit')  

class WalkForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('No Fossil Fuel', 'No Fossil Fuel')])
  submit = SubmitField('Submit')  

capp/carbon_app/__init__.py
#

capp/carbon_app/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, flash
from capp.models import Transport
from capp import db
from datetime import timedelta, datetime
from flask_login import login_required, current_user
from capp.carbon_app.forms import BusForm, CarForm, PlaneForm, FerryForm, MotorbikeForm, BicycleForm, WalkForm

carbon_app=Blueprint('carbon_app',__name__)

#Emissions factor per transport in kg per passemger km
#Data from: http://efdb.apps.eea.europa.eu/?source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%2C%22display_type%22%3A%22tabular%22%7D
efco2={'Bus':{'Diesel':0.10231,'CNG':0.08,'Petrol':0.10231,'No Fossil Fuel':0},
    'Car':{'Petrol':0.18592,'Diesel':0.16453,'No Fossil Fuel':0},
    'Plane':{'Petrol':0.24298},
    'Ferry':{'Diesel':0.11131, 'CNG':0.1131, 'No Fossil Fuel':0},
    'Motorbike':{'Petrol':0.09816,'No Fossil Fuel':0},
    'Scooter':{'No Fossil Fuel':0},
    'Bicycle':{'No Fossil Fuel':0},
    'Walk':{'No Fossil Fuel':0}}
efch4={'Bus':{'Diesel':2e-5,'CNG':2.5e-3,'Petrol':2e-5,'No Fossil Fuel':0},
    'Car':{'Petrol':3.1e-4,'Diesel':3e-6,'No Fossil Fuel':0},
    'Plane':{'Petrol':1.1e-4},
    'Ferry':{'Diesel':3e-5, 'CNG':3e-5,'No Fossil Fuel':0},
    'Motorbike':{'Petrol':2.1e-3,'No Fossil Fuel':0},
    'Scooter':{'No Fossil Fuel':0},
    'Bicycle':{'No Fossil Fuel':0},
    'Walk':{'No Fossil Fuel':0}}

#Carbon app, main page
@carbon_app.route('/carbon_app')
@login_required
def carbon_app_home():
    return render_template('carbon_app/carbon_app.html', title='carbon_app')

#New entry bus
@carbon_app.route('/carbon_app/new_entry_bus', methods=['GET','POST'])
@login_required
def new_entry_bus():
    form = BusForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Bus'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_bus.html', title='new entry bus', form=form)

#New entry car
@carbon_app.route('/carbon_app/new_entry_car', methods=['GET','POST'])
@login_required
def new_entry_car():
    form = CarForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Car'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_car.html', title='new entry car', form=form)    

#New entry plane
@carbon_app.route('/carbon_app/new_entry_plane', methods=['GET','POST'])
@login_required
def new_entry_plane():
    form = PlaneForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Plane'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_plane.html', title='new entry plane', form=form)  

#New entry ferry
@carbon_app.route('/carbon_app/new_entry_ferry', methods=['GET','POST'])
@login_required
def new_entry_ferry():
    form = FerryForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Ferry'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_ferry.html', title='new entry ferry', form=form)     

#New entry motorbike
@carbon_app.route('/carbon_app/new_entry_motorbike', methods=['GET','POST'])
@login_required
def new_entry_motorbike():
    form = MotorbikeForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Motorbike'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_motorbike.html', title='new entry motorbike', form=form) 

#New entry bicycle
@carbon_app.route('/carbon_app/new_entry_bicycle', methods=['GET','POST'])
@login_required
def new_entry_bicycle():
    form = BicycleForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Bicycle'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_bicycle.html', title='new entry bicycle', form=form)

#New entry walk
@carbon_app.route('/carbon_app/new_entry_walk', methods=['GET','POST'])
@login_required
def new_entry_walk():
    form = WalkForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Walk'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        ch4 = float(kms) * efch4[transport][fuel]
        total = co2+ch4

        co2 = float("{:.2f}".format(co2))
        ch4 = float("{:.2f}".format(ch4))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, ch4=ch4, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_walk.html', title='new entry walk', form=form)

#Your data
@carbon_app.route('/carbon_app/your_data')
@login_required
def your_data():
    #Table
    entries = Transport.query.filter_by(author=current_user). \
        filter(Transport.date> (datetime.now() - timedelta(days=5))).\
        order_by(Transport.date.desc()).order_by(Transport.transport.asc()).all()
    return render_template('carbon_app/your_data.html', title='your_data', entries=entries)

#Delete emission
@carbon_app.route('/carbon_app/delete-emission/<int:entry_id>')
def delete_emission(entry_id):
    entry = Transport.query.get_or_404(int(entry_id))
    db.session.delete(entry)
    db.session.commit()
    flash("Entry deleted", "success")
    return redirect(url_for('carbon_app.your_data'))
    
  

capp/methodology/routes.py
from flask import render_template, Blueprint

methodology=Blueprint('methodology',__name__)

@methodology.route('/methodology')
def methodology_home():
  return render_template('methodology.html', title='methodology')

capp/templates/carbon_app/carbon_app.html
{% extends "layout.html" %}
{% block content %}

    <!-- Header -->
    <section class="section_header_carbon_app">
        <div class="container">
    
        <div class="header_carbon_app">
            <div class="box"> 
            <h1 style="font-size:55px;"><span class="text-logo"> Carbon App Calculator</span></h1>
            <p style="text-align:left;">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat dolores quos asperiores repellendus facilis cum illo aperiam odit doloremque nostrum. Totam excepturi labore voluptatibus iusto sapiente quisquam consectetur optio magnam voluptates omnis vel officia alias distinctio quas laborum reiciendis ratione inventore veniam, cupiditate doloribus dolore, eius natus a. Magni inventore consequuntur voluptas reprehenderit perferendis! Molestias aspernatur rem autem aut temporibus.
            </p>
            <div class="container_buttons_links_header_carbon_app">
                <div class="btn">
                    <a href="{{url_for('methodology.methodology_home')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">Methodology</a>
                </div>
                <div class="btn">
                    <a href="{{url_for('carbon_app.your_data')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#007bff;">Your data</a>
                </div>
            </div>  
            </div>
            <div class="box">
            <img 
                src="{{url_for('static', filename='icons/calculator.svg')}}"
                width="325" 
                height="325"
                alt=""/>
            </div>
        </div>
        
        </div>
    </section> 

    <!-- carbon_app_new_entry_main -->
    <section class="section_carbon_app_new_entry_main">
    <div class="container">
  
      <div class="carbon_app_new_entry_main" style="display:block;">
        <br>
        <h3 style="text-align:center;">Please, select your mean of conveyance in the boxes below</h3>     
      </div>
  
      <div class="carbon_app_new_entry_main">
          <div class="box">
            <div class="h1 mb-3" style="text-align: center;">
                <i class="fa-solid fa-bus"></i>
            </div>
            <h3>Bus</h3>
            <p>Please, enter your kilometers by using the bus.
            </p>
            <div class="section_container_buttons_carbon_app_new_entry_main">
              <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_bus')}}">New Entry</a>
            </div> 
          </div>
          <div class="box">
            <div class="h1 mb-3" style="text-align: center;">
                <i class="fa-solid fa-car"></i>
            </div>
            <h3>Car</h3>
            <p>Please, enter your kilometers by using the car.
            </p>
            <div class="section_container_buttons_carbon_app_new_entry_main">
              <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_car')}}">New Entry</a>
            </div> 
          </div>           
          <div class="box">
            <div class="h1 mb-3" style="text-align: center;">
                <i class="fa-solid fa-plane"></i>
            </div>
            <h3>Plane</h3>
            <p>Please, enter your kilometers by using the plane.
            </p>
            <div class="section_container_buttons_carbon_app_new_entry_main">
              <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_plane')}}">New Entry</a>
            </div> 
          </div>
          <div class="box">
            <div class="h1 mb-3" style="text-align: center;">
                <i class="fa-solid fa-ship"></i>
            </div>
            <h3>Ferry</h3>
            <p>Please, enter your kilometers by using the ferry.
            </p>
            <div class="section_container_buttons_carbon_app_new_entry_main">
              <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_ferry')}}">New Entry</a>
            </div> 
          </div>      
      </div>

      <div class="carbon_app_new_entry_main">
        <div class="box">
          <div class="h1 mb-3" style="text-align: center;">
            <i class="fa-solid fa-motorcycle"></i>
          </div>
          <h3>Motorbike</h3>
          <p>Please, enter your kilometers by using the motocycle.
          </p>
          <div class="section_container_buttons_carbon_app_new_entry_main">
            <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_motorbike')}}">New Entry</a>
          </div> 
        </div>    
        <div class="box">
          <div class="h1 mb-3" style="text-align: center;">
            <i class="fa-solid fa-bicycle"></i>
          </div>
          <h3>Bicycle</h3>
          <p>Please, enter your kilometers by using the bicycle.
          </p>
          <div class="section_container_buttons_carbon_app_new_entry_main">
            <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_bicycle')}}">New Entry</a>
          </div> 
        </div>
        <div class="box">
          <div class="h1 mb-3" style="text-align: center;">
            <i class="fa-solid fa-person-walking"></i>
          </div>
          <h3>Walk</h3>
          <p>Please, enter your kilometers by walking.
          </p>
          <div class="section_container_buttons_carbon_app_new_entry_main">
            <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_walk')}}">New Entry</a>
          </div> 
        </div> 
        <div class="box" style="background-color:#c5c8d9;">
        </div>      
    </div>
  
    </div>          
    </section>
       

{% endblock content %}

capp/templates/carbon_app/new_entry_bicycle.html
{% extends "layout.html" %}
{% block content %}

<section class="new_entry">
  <div class="container">
      <div class="box">

      </div>
      <div class="box">   
        <div class="h1 mb-3" style="text-align: center;">
          <i class="fa-solid fa-bicycle"></i>
        </div>
        <h3>Bicycle</h3>
        <p>
          <ol style="text-align: left;">
            <li>
              Please, enter the number of kilometers.
            </li>
          </ol>
        </p>
          <form method="POST" action="">
              {{ form.csrf_token }}
              <fieldset class="form-group">

                <div class="form-group">
                    {{ form.kms.label(class="form-control-label") }}
                    {% if form.kms.errors %}
                        {{ form.kms(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.kms.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.kms(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.fuel_type.label(class="form-control-label") }}
                    {% if form.fuel_type.errors %}
                        {{ form.fuel_type(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.fuel_type.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.fuel_type(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

              </fieldset>
              </br>
              <div class="form-group">
                {{ form.submit(class="btn_carbon_app_new_entry_main") }}
              </div>
          </form>
      </div>
      <div class="box">

      </div>
  </div>
</section> 

        
{% endblock content %}

capp/templates/carbon_app/new_entry_bus.html
{% extends "layout.html" %}
{% block content %}

<section class="new_entry">
  <div class="container">
      <div class="box">

      </div>
      <div class="box">   
        <div class="h1 mb-3" style="text-align: center;">
          <i class="fa-solid fa-bus"></i>
        </div>
        <h3>Bus</h3>
        <p>
          <ol style="text-align: left;">
            <li>
              Please, enter the number of kilometers.
            </li>
            <li>
              Please, select the type of fuel
            </li>
          </ol>
        </p>
          <form method="POST" action="">
              {{ form.csrf_token }}
              <fieldset class="form-group">

                <div class="form-group">
                    {{ form.kms.label(class="form-control-label") }}
                    {% if form.kms.errors %}
                        {{ form.kms(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.kms.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.kms(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.fuel_type.label(class="form-control-label") }}
                    {% if form.fuel_type.errors %}
                        {{ form.fuel_type(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.fuel_type.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.fuel_type(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

              </fieldset>
              </br>
              <div class="form-group">
                {{ form.submit(class="btn_carbon_app_new_entry_main") }}
              </div>
          </form>
      </div>
      <div class="box">

      </div>
  </div>
</section> 

        
{% endblock content %}

capp/templates/carbon_app/new_entry_car.html
{% extends "layout.html" %}
{% block content %}

<section class="new_entry">
  <div class="container">
      <div class="box">

      </div>
      <div class="box">   
        <div class="h1 mb-3" style="text-align: center;">
          <i class="fa-solid fa-car"></i>
        </div>
        <h3>Car</h3>
        <p>
          <ol style="text-align: left;">
            <li>
              Please, enter the number of kilometers.
            </li>
            <li>
              Please, select the type of fuel
            </li>
          </ol>
        </p>
          <form method="POST" action="">
              {{ form.csrf_token }}
              <fieldset class="form-group">

                <div class="form-group">
                    {{ form.kms.label(class="form-control-label") }}
                    {% if form.kms.errors %}
                        {{ form.kms(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.kms.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.kms(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.fuel_type.label(class="form-control-label") }}
                    {% if form.fuel_type.errors %}
                        {{ form.fuel_type(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.fuel_type.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.fuel_type(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

              </fieldset>
              </br>
              <div class="form-group">
                {{ form.submit(class="btn_carbon_app_new_entry_main") }}
              </div>
          </form>
      </div>
      <div class="box">

      </div>
  </div>
</section> 

        
{% endblock content %}

capp/templates/carbon_app/new_entry_ferry.html
{% extends "layout.html" %}
{% block content %}

<section class="new_entry">
  <div class="container">
      <div class="box">

      </div>
      <div class="box">   
        <div class="h1 mb-3" style="text-align: center;">
          <i class="fa-solid fa-ship"></i>
        </div>
        <h3>Ferry</h3>
        <p>
          <ol style="text-align: left;">
            <li>
              Please, enter the number of kilometers.
            </li>
            <li>
              Please, select the type of fuel
            </li>
          </ol>
        </p>
          <form method="POST" action="">
              {{ form.csrf_token }}
              <fieldset class="form-group">

                <div class="form-group">
                    {{ form.kms.label(class="form-control-label") }}
                    {% if form.kms.errors %}
                        {{ form.kms(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.kms.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.kms(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.fuel_type.label(class="form-control-label") }}
                    {% if form.fuel_type.errors %}
                        {{ form.fuel_type(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.fuel_type.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.fuel_type(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

              </fieldset>
              </br>
              <div class="form-group">
                {{ form.submit(class="btn_carbon_app_new_entry_main") }}
              </div>
          </form>
      </div>
      <div class="box">

      </div>
  </div>
</section> 

        
{% endblock content %}

capp/templates/carbon_app/your_data.html
{% extends "layout.html" %}
{% block content %}

    <!-- New Entry Section -->
    <section class="main_menu">
      <div class="container">
          <div class="box">

          </div>
          <div class="box"> 
              <div class="container_buttons_links_main_menu">
                  <div class="btn">
                      <a href="{{ url_for('carbon_app.carbon_app_home') }}" class="btn_carbon_app_new_entry_main">New Entry</a>
                  </div>   
              </div>        
          </div>
          <div class="box">

          </div>
      </div>
    </section> 

    <!-- Table Section -->
    <section class="table_main">
    <div class="container">
        <div class="box">

        </div>
        <div class="box">  
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div> 
                    {% endfor %}
                {% endif %}
            {% endwith %}         
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">User</th>
                        <th scope="col">Date</th>
                        <th scope="col">Kilometres</th>
                        <th scope="col">Transport</th>
                        <th scope="col">Fuel</th>
                        <th scope="col">Co2</th>
                        <th scope="col">Ch4</th>
                        <th scope="col">Total</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entry in entries %}
                        <tr>
                            <th scope="row">{{ current_user.username }}</th>
                            <td>{{ entry.date.strftime("%m-%d-%Y") }}</td>
                            <td>{{ entry.kms }}</td>
                            <td>{{ entry.transport }}</td>
                            <td>{{ entry.fuel }}</td>
                            <td>{{ entry.co2 }}</td>
                            <td>{{ entry.ch4 }}</td>
                            <td>{{ entry.total }}</td>
                            <td><a href="{{ url_for('carbon_app.delete_emission', entry_id = entry.id) }}" class="btn btn-outline-danger btn-sm">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>       
        </div>
        <div class="box">

        </div>
    </div>
    </section> 

        
{% endblock content %}